<a href="https://colab.research.google.com/github/chiahaofan/Senior-project/blob/learncode/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
Matrix = np.array([1, 2, 3, 4])
Matrix2 = np.array([[1,2,3,4], [5,6,7,8], [10,11,12,13]])
print('Matrix與Matrix2元素:\n', Matrix, end='\n')
print(Matrix2)
print('Matrix維度:', np.ndim(Matrix), ",", np.ndim(Matrix2))
print('Matrix元組(tuple):', Matrix.shape, ",", Matrix2.shape)

Matrix與Matrix2元素:
 [1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]
Matrix維度: 1 , 2
Matrix元組: (4,) , (3, 4)
